### ISSUE TITLE
zypper: get-files gives a ;-separated list of paths instead of an array of strings

### ISSUE THREAD

**Issue by aleixpol** [hughsie/PackageKit#351] opened 2019-11-07 15:40 UTC
What pkcon gets:
![Screenshot_20191107_163742](https://user-images.githubusercontent.com/1282478/68403390-27e3c600-017d-11ea-84bb-da4b3cd23f7c.png)

Original bug:
https://bugs.kde.org/show_bug.cgi?id=412986

**Comment by aleixpol** [comment] 2019-11-07 15:56
See https://github.com/hughsie/PackageKit/blob/master/backends/zypp/pk-backend-zypp.cpp#L2289

**Comment by Vogtinator** [comment] 2019-11-07 18:17
The issue is actually in a different method: https://github.com/hughsie/PackageKit/blob/6dc4d503cfab4c0270924ddf8acfefb4f06d47fa/backends/zypp/pk-backend-zypp.cpp#L3368

It looks like it was not properly adapted to the API change a few years ago: https://github.com/hughsie/PackageKit/commit/c0f93fb6119be8fe821a9f0191a2e655dc529d30

@JonathanKang Please have a look.

**Comment by JonathanKang** [comment] 2019-11-08 03:26
Fixed by 98dd535f5.

**Closed by JonathanKang** 2019-11-08 03:26 UTC
