### ISSUE TITLE
UpdatesChanged is not emitted when available updates list changes

### ISSUE THREAD

**Issue by antonio-rojas** [hughsie/PackageKit#169] opened 2016-10-02 10:43 UTC
When the available updates list changes (eg. by running 'pkcon get-updates' when new updates are available) the UpdatesChanged signal is not emitted. This breaks update notifiers that rely on this signal (such as Plasma Discover).
This affects the alpm backend, I haven't tested other backends.

**Comment by aleixpol** [comment] 2016-10-02 20:29
I can reproduce this. Also with aptcc as well

**Comment by Appadeia** [comment] 2020-03-25 01:06
This issue should be closed since the fix is merged. Wonder why GitHub didn't pick up the mention as a "will close this issue" mention.

**Comment by aleixpol** [comment] 2020-03-25 12:06
I'd say it's fixed too for aptcc now, at least our users are getting the updates notifications. I'd say let's just close it for now.

**Closed by aleixpol** 2020-03-25 12:06 UTC
Labels: Backend: alpm (Arch Linux), Backend: aptcc (Debian GNU/Linux)
