### ISSUE TITLE
pkcon does not distinguish between unavailable and already installed packages

### ISSUE THREAD

**Issue by Keno** [hughsie/PackageKit#172] opened 2016-10-20 20:57 UTC
E.g. in the following command. I would have expected the error to complain that `m4` was already installed, not that it couldn't be found:
```
keno@anubis:~$ ./PackageKit/client/pkcon install m4
Resolving                     [=========================]         Package not found: m4
Command failed: This tool could not find any available package: No packages were found
keno@anubis:~$ ./PackageKit/client/pkcon install foobar
Resolving                     [=========================]         Package not found: foobar
Command failed: This tool could not find any available package: No packages were found
```

**Comment by aleixpol** [comment] 2016-10-20 21:50
Can you please specify which distribution/backend are you using?

**Comment by Keno** [comment] 2016-10-20 22:20
Sorry!
```
keno@anubis:~$ pkcon backend-details
Name:		aptcc
Description:	APTcc
Author:	Daniel Nicoletti <dantti12@gmail.com>
keno@anubis:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"
```

**Comment by aleixpol** [comment] 2016-10-20 22:27
Duplicate of #168

**Closed by aleixpol** 2016-10-20 22:27 UTC
