### ISSUE TITLE
SIGSEGV in `pk_dbus_get_uid()`

### ISSUE THREAD

**Issue by paulmenzel** [hughsie/PackageKit#439] opened 2020-11-15 04:41 UTC
Using Debian Sid/unstable with *packagekit* 1.2.1-1, `coredumpctl` lists crashes with a segmentation fault.

*   [GDB’s full backtrace from all threads](https://github.com/hughsie/PackageKit/files/5541865/20201115.packagekitd.sigsegv.gdb-taabtf.txt)

```
[…]
Core was generated by `/usr/libexec/packagekitd'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000556e780c4631 in pk_dbus_get_uid (dbus=0x556e78eb4920, sender=sender@entry=0x7fb66000f010 ":1.87") at ../src/pk-dbus.c:81
81	../src/pk-dbus.c: Datei oder Verzeichnis nicht gefunden.
[Current thread is 1 (Thread 0x7fb66f3468c0 (LWP 791))
(gdb) bt
#0  0x0000556e780c4631 in pk_dbus_get_uid (dbus=0x556e78eb4920 [PkDbus], sender=sender@entry=0x7fb66000f010 ":1.87") at ../src/pk-dbus.c:81
#1  0x0000556e780ddd5d in pk_engine_is_proxy_unchanged (pac=0x556e78ef6fc0 "", no_proxy=0x556e78ef7460 "", proxy_socks=0x556e78f19410 "", proxy_ftp=0x0, proxy_https=0x556e78f194d0 "", proxy_http=0x0, sender=0x7fb66000f010 ":1.87", engine=0x556e78eaa1a0 [PkEngine]) at ../src/pk-engine.c:598
#2  pk_engine_set_proxy (context=0x556e78ed12d0 [GDBusMethodInvocation], pac=<optimized out>, no_proxy=<optimized out>, proxy_socks=<optimized out>, proxy_ftp=0x0, proxy_https=<optimized out>, proxy_http=0x0, engine=0x556e78eaa1a0 [PkEngine]) at ../src/pk-engine.c:686
#3  pk_engine_daemon_method_call (connection_=<optimized out>, sender=sender@entry=0x7fb66000f010 ":1.87", object_path=object_path@entry=0x7fb6640014e0 "/org/freedesktop/PackageKit", interface_name=interface_name@entry=0x7fb660008460 "org.freedesktop.PackageKit", method_name=method_name@entry=0x7fb66000ec00 "SetProxy", parameters=parameters@entry=0x7fb66000cb20, invocation=0x556e78ed12d0 [GDBusMethodInvocation], user_data=0x556e78eaa1a0) at ../src/pk-engine.c:1438
#4  0x00007fb66fe37f1e in call_in_idle_cb (user_data=<optimized out>) at ../../../gio/gdbusconnection.c:4890
#5  0x00007fb66ffb6adf in g_main_dispatch (context=0x556e78ea7d30) at ../../../glib/gmain.c:3325
#6  g_main_context_dispatch (context=0x556e78ea7d30) at ../../../glib/gmain.c:4043
#7  0x00007fb66ffb6e88 in g_main_context_iterate (context=0x556e78ea7d30, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../../../glib/gmain.c:4119
#8  0x00007fb66ffb717b in g_main_loop_run (loop=loop@entry=0x556e78ea7e20) at ../../../glib/gmain.c:4317
#9  0x0000556e780c3d21 in main (argc=<optimized out>, argv=<optimized out>) at ../src/pk-main.c:242
```

**Comment by hughsie** [comment] 2020-11-15 09:15
Does 30b22c0f06970c934b3e6f6ea0328c589548850c fix things for you?

**Comment by mr-c** [comment] 2020-12-27 11:18
Hello, another Debian user using the same version (1.2.1-1). I experienced the same issue with the same backtrace of the core dump. I think this is a duplicate of #436 and the patch in https://github.com/hughsie/PackageKit/pull/437 a.k.a  30b22c0 fixes it for me. Thanks!

**Closed** 2020-12-27 11:24 UTC

**Comment by paulmenzel** [comment] 2020-12-27 13:11
Yes, it does not crash anymore with [Debian package version 1.2.2-1](https://metadata.ftp-master.debian.org/changelogs//main/p/packagekit/packagekit_1.2.2-2_changelog), which has the patch applied. Thank you everyone.
