### ISSUE TITLE
Installations of packages are not subject to validation of credentials

### ISSUE THREAD

**Issue by Ricky-Tigg** [hughsie/PackageKit#396] opened 2020-04-23 12:25 UTC
**OS**: Fedora; **Component** (from system): PackageKit-command-not-found.x86_64 1.1.13-2.fc32

Installations of packages are not subject to validation of credentials:
```
[yk@localhost ~]$ firejail --version
bash: firejail: command not found...
Install package 'firejail' to provide command 'firejail'? [N/y] y
 * Waiting in queue... 
 * Loading list of packages.... 
The following packages have to be installed:
 firejail-0.9.62-1.fc32.x86_64	Linux namespaces sandbox program
Proceed with changes? [N/y] y
 * Waiting in queue... 
 * Waiting for authentication... 
 * Waiting in queue... 
 * Downloading packages... 
 * Requesting data... 
 * Testing changes... 
 * Installing packages... 
firejail version 0.9.62
```
As comparison in my system, installations relying on RPM and DNF tools, are subject to validation of credentials as illustrated 
```
$ id
uid=1000(yk) gid=1000(yk) groups=1000(yk),10(wheel) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
$ sudo dnf -y install firejail
[sudo] password for yk:
```

**Comment by hughsie** [comment] 2020-04-23 13:04
Is your account marked as a administrator? If so, installing a signed package from a repo you trust without authentication is operating as designed.

**Comment by Ricky-Tigg** [comment] 2020-04-24 12:29
I had presumed wrong; I expected this tool to observe as well the protocol revealed in command prompt, like DNF and RPM do.
```
[yk@localhost ~]$ sudo -nv
sudo: a password is required
```
My `id` may show that information you queried; user named _yk_ belongs to _wheel_ group, which grants **elevated privileges** – `sudo`, but does not belong to _root_ group. Its rights are:
```
[yk@localhost ~]# sudo -lU yk | tail -2
User yk may run the following commands on localhost:
    (ALL) ALL
```

**Comment by Conan-Kudo** [comment] 2020-04-24 12:32
This is working as intended. The `wheel` group is what we use to handle the automated privilege grant.

**Closed by Conan-Kudo** 2020-04-24 12:32 UTC
